### ISSUE TITLE
fifa 22

### ISSUE THREAD

**Issue by cptmacp** [xAranaktu/FIFASquadFileDownloader#1]
can this be used for fifa 22?

CONTENT_URL = "https://fifa21.content.easports.com/fifa/fltOnlineAssets/21D4F1AC-91A3-458D-A64E-895AA6D871D1/2021/"

maybe make this fifa22 instead of fifa 

21

anyways here is the latest squad and some dlc squad asset from fifa 22 game 
[settings.zip](https://github.com/xAranaktu/FIFASquadFileDownloader/files/7214276/settings.zip)

**Comment by xAranaktu** [comment]
`https://fifa22.content.easports.com/fifa/fltOnlineAssets/22747632-e3df-4904-b3f6-bb0035736505/2022/`

:)

[Script updated for FIFA 22](https://github.com/xAranaktu/FIFASquadFileDownloader/commit/62ffeb323aea2422fe4bb7b7a8ae04fbe4117d02)

**Comment by cptmacp** [comment]
hey !

thanks @xAranaktu 

let me test it and report back

any work progres on initial cheat table for 22?

**Comment by cptmacp** [comment]
![2](https://user-images.githubusercontent.com/11556463/134720821-bfdd89c9-422d-4416-8f7a-3041fba393e2.png)
![squad](https://user-images.githubusercontent.com/11556463/134720834-a1379a31-7235-4d27-b6b0-c1cd7f8b2f63.png)

ok 

seems to work good

**Comment by xAranaktu** [comment]
> any work progres on initial cheat table for 22?

First version is already out for Patrons. Public release is delayed by 7 days, as always.
