### ISSUE TITLE
FC24 PC squads problem

### ISSUE THREAD

**Issue by dany007119966** [xAranaktu/FIFASquadFileDownloader#10]
downloading squads works ok but on **fc24** game menu when go to profile load then squads always showing that file is corrupted 
can y fix it ? or what a problem ?

i use this 

**Squads20230925000000**
but message is same

![hgjffgjd](https://github.com/xAranaktu/FIFASquadFileDownloader/assets/146432222/45be84c5-7acf-4647-93bf-54b4fcb616fc)

**Comment by xAranaktu** [comment]
Problem with unpacking the file. I don't know atm. Maybe will be fixed, maybe not.

**Comment by dany007119966** [comment]
now its working thx for fix.

**Comment by JoeyJoeJoe141** [comment]
wow~ thx for fix.
