### ISSUE TITLE
just for fifa 24 ?

### ISSUE THREAD

**Issue by rasss98** [xAranaktu/FIFASquadFileDownloader#8]
hi , this is just work for fc24 or we can use for fifa 23 ? if not work , where i can download latest fifa 23 squad ?

**Comment by xAranaktu** [comment]
It's currently updated for FC 24. You can still anytime just check the commit history and use older version of the script.
https://github.com/xAranaktu/FIFASquadFileDownloader/blob/3272694485e341aa82b2407621ef3a5949756f34/main.py

**Comment by Landy005** [comment]
does this work to take the latest fifa24 squads for fifa22?
