### ISSUE TITLE
Squad Upate stopped working recently (10/9/2023)

### ISSUE THREAD

**Issue by clcelvis** [xAranaktu/FIFASquadFileDownloader#9]
All codes work perfectly. However, when I load the save in fifa 23 (pc version), there were no change when compare to the default squad.

It worked two weeks ago. Is it the issue relating to EAFC24 server?

**Comment by xAranaktu** [comment]
Not sure what you mean. I've downloaded the `Squads20230907000000` and I don't have any troubles with loading it in game.
But yea, the latest version of the script is already updated for EAFC 24 and the squadfiles for EAFC 24 will not work in FIFA 23.

**Comment by clcelvis** [comment]
Thank you for the prompt reply. I will wait for the EAFC 24 from xbox pass!

**Comment by xAranaktu** [comment]
If you need the latest FIFA 23 squadfile then you can still use older version of the script https://github.com/xAranaktu/FIFASquadFileDownloader/blob/3272694485e341aa82b2407621ef3a5949756f34/main.py
